replace /tmp/v with

diff --git a/build.yaml b/build.yaml
--- a/build.yaml
+++ b/build.yaml
@@ -14,6 +14,10 @@ common_cli:
     #!/bin/bash -l
     set -x
     set -e
+
+    # define the directory for our virtualenv
+    export venv=/tmp/v
+
     os() {
       # Determine OS platform
       source /etc/os-release
@@ -73,15 +77,15 @@ common_cli:
     # http://stackoverflow.com/questions/10813538/shebang-line-limit-in-bash-and-linux-kernel
     # https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/20
     # So we will place the virtualenv in /tmp/v instead
-    sudo rm -rf /tmp/v
+    sudo rm -rf \$venv
     sudo rm -f results.xml
     sudo rm -f trial.log
     sudo rm -rf _trial_temp/
 
   setup_venv: &setup_venv |
     # setup the new venv
-    virtualenv -p python2.7 --clear /tmp/v
-    . /tmp/v/bin/activate
+    virtualenv -p python2.7 --clear \$venv
+    . \${venv}/bin/activate
 
   setup_pip_cache: &setup_pip_cache |
     . /tmp/pip.sh
@@ -121,7 +125,7 @@ common_cli:
   run_sphinx: &run_sphinx |
     parse_logs python setup.py --version
     cd docs
-    set +e #don't abort at the first failure
+    set +e #dont abort at the first failure
     let status=0
     # check spelling
     parse_logs sphinx-build -d _build/doctree -b spelling . _build/spelling
@@ -145,11 +149,11 @@ common_cli:
 
   run_trial_with_coverage: &run_trial_with_coverage |
     # Consume the MODULE parameter set in the job configuration
-    coverage run /tmp/v/bin/trial --reporter=subunit \$MODULE 2>&1 | parse_logs tee trial.log
+    coverage run \$venv/bin/trial --reporter=subunit \$MODULE 2>&1 | parse_logs tee trial.log
 
   run_trial_for_storage_drivers_with_coverage: &run_trial_for_storage_drivers_with_coverage |
     # Consume the MODULE parameter set in the job configuration
-    sudo -E /tmp/v/bin/coverage run /tmp/v/bin/trial --reporter=subunit --testmodule \$MODULE 2>&1 | parse_logs tee trial.log
+    sudo -E \$venv/bin/coverage run \$venv/bin/trial --reporter=subunit --testmodule \$MODULE 2>&1 | parse_logs tee trial.log
 
   setup_authentication: &setup_authentication |
     # acceptance tests rely on this file existing
@@ -164,14 +168,14 @@ common_cli:
 
   run_acceptance_aws_tests: &run_acceptance_aws_tests |
     # we gather the return code, but make sure we come out of these tests with '0'
-    parse_logs /tmp/v/bin/python admin/run-acceptance-tests --distribution \${DISTRIBUTION_NAME} --provider aws --dataset-backend aws --branch \${TRIGGERED_BRANCH} --build-server  http://\$(wget -qO- http://instance-data/latest/meta-data/public-ipv4)  --config-file /tmp/acceptance.yaml \${ACCEPTANCE_TEST_MODULE} ; RC=\$?
+    parse_logs \$venv/bin/python admin/run-acceptance-tests --distribution \${DISTRIBUTION_NAME} --provider aws --dataset-backend aws --branch \${TRIGGERED_BRANCH} --build-server  http://\$(wget -qO- http://instance-data/latest/meta-data/public-ipv4)  --config-file /tmp/acceptance.yaml \${ACCEPTANCE_TEST_MODULE} ; RC=\$?
 
   run_acceptance_rackspace_tests: &run_acceptance_rackspace_tests |
     # we gather the return code, but make sure we come out of these tests with '0'
-    parse_logs /tmp/v/bin/python admin/run-acceptance-tests --distribution \${DISTRIBUTION_NAME} --provider rackspace --dataset-backend rackspace --branch \${TRIGGERED_BRANCH} --build-server  http://\$(wget -qO- http://instance-data/latest/meta-data/public-ipv4)  --config-file /tmp/acceptance.yaml \${ACCEPTANCE_TEST_MODULE} ; RC=\$?
+    parse_logs \$venv/bin/python admin/run-acceptance-tests --distribution \${DISTRIBUTION_NAME} --provider rackspace --dataset-backend rackspace --branch \${TRIGGERED_BRANCH} --build-server  http://\$(wget -qO- http://instance-data/latest/meta-data/public-ipv4)  --config-file /tmp/acceptance.yaml \${ACCEPTANCE_TEST_MODULE} ; RC=\$?
 
   run_client_tests: &run_client_tests |
-    parse_logs /tmp/v/bin/python admin/run-client-tests --distribution \${DISTRIBUTION_NAME} --branch \${TRIGGERED_BRANCH} --build-server  http://\$(wget -qO- http://instance-data/latest/meta-data/public-ipv4) ; RC=\$?
+    parse_logs \$venv/bin/python admin/run-client-tests --distribution \${DISTRIBUTION_NAME} --branch \${TRIGGERED_BRANCH} --build-server  http://\$(wget -qO- http://instance-data/latest/meta-data/public-ipv4) ; RC=\$?
 
   disable_selinux: &disable_selinux |
     sudo /usr/sbin/setenforce 0
@@ -181,11 +185,11 @@ common_cli:
 
   build_sdist: &build_sdist  |
     # package the goodies
-    parse_logs /tmp/v/bin/python setup.py sdist
+    parse_logs \$venv\bin/python setup.py sdist
 
   build_package: &build_package  |
     # and build a rpm/deb package using docker
-    parse_logs /tmp/v/bin/python admin/build-package --destination-path repo --distribution \${DISTRIBUTION_NAME} /flocker/dist/Flocker-\${FLOCKER_VERSION}.tar.gz
+    parse_logs \$venv/bin/python admin/build-package --destination-path repo --distribution \${DISTRIBUTION_NAME} /flocker/dist/Flocker-\${FLOCKER_VERSION}.tar.gz
 
   build_repo_metadata: &build_repo_metadata |
     # the acceptance tests look for a package in a yum repository,
