try out support for colored logging in jenkins

diff --git a/build.yaml b/build.yaml
--- a/build.yaml
+++ b/build.yaml
@@ -1,5 +1,5 @@
-# vim: ft=yaml:fdm=indent
-# To modify an existing job, simply update the jobs_type: dictionary
+# vim ft=yaml:fdm=indent
+# Toodify an existing job, simply update the jobs_type: dictionary
 # commit, push
 # Then click 'deploy' on the jenkins job related to this repository
 # available on the jenkins homepage.
@@ -14,9 +14,69 @@ common_cli:
     #!/bin/bash
     set -x
     set -e
+    os() {
+      # Determine OS platform
+      UNAME=\$(uname | tr "[:upper:]" "[:lower:]")
+      # If Linux, try to determine specific distribution
+      if [ "\$UNAME" == "linux" ]; then
+          # If available, use LSB to identify distribution
+          if [ -f /etc/lsb-release -o -d /etc/lsb-release.d ]; then
+              export DISTRO=\$(lsb_release -i | cut -d: -f2 | sed s/'^\t'//)
+          # Otherwise, use release info file
+          else
+              export DISTRO=\$(ls -d /etc/[A-Za-z]*[_-][rv]e[lr]* | grep -v "lsb" | cut -d'/' -f3 | cut -d'-' -f1 | cut -d'_' -f1)
+          fi
+      fi
+      # For everything else (or if above failed), just use generic identifier
+      if [ "\$DISTRO" == "" ]
+      then
+        export DISTRO=\$UNAME
+      fi
+      unset UNAME
+      echo \$DISTRO
+    }
+    # add a function that we can consume to colorise output
+    # https://wiki.archlinux.org/index.php/Color_Bash_Prompt
+    parse_logs() {
+      # ubuntu defaults to mawk, which causes some things to break
+      if [ "\$(os)" == "Ubuntu" ]
+      then
+        alias awk='mawk -W interactive'
+      fi
+
+      "\$@" | awk '
+        # exceptions to rules below, these are always printed black
+        /.*reading.sources.*error_pages.404.*/ {print "\\033[0;30m" \$0 "\\033[0;30m";  next }
+        /.*writing.output.*error_pages.404.*/ {print "\\033[0;30m" \$0 "\\033[0;30m";  next }
+        /.*errors.py.*/ {print "\\033[0;30m" \$0 "\\033[0;30m";  next }
+
+        # red lines
+        /.*exception.*/ {print "\\033[0;31m" \$0 "\\033[0;30m";  next }
+        /.*Exception.*/ {print "\\033[0;31m" \$0 "\\033[0;30m";  next }
+        /.*fail.*/      {print "\\033[0;31m" \$0 "\\033[0;30m";  next }
+        /.*ERROR.*/     {print "\\033[0;31m" \$0 "\\033[0;30m";  next }
+        /.*error.*/     {print "\\033[0;31m" \$0 "\\033[0;30m";  next }
+        /build finished with problems./     {print "\\033[0;31m" \$0 "\\033[0;30m";  next }
+        /return 1/     {print "\\033[0;31m" \$0 "\\033[0;30m";  next }
+
+        # yellow lines
+        /.*Warning.*/   {print "\\033[0;33m" \$0 "\\033[0;30m";  next }
+        /.*warning.*/   {print "\\033[0;33m" \$0 "\\033[0;30m";  next }
+        /.*skip.*/      {print "\\033[0;33m" \$0 "\\033[0;30m";  next }
+
+        # green lines
+        /.*succeeded.*/  {print "\\033[0;32m" \$0 "\\033[0;30m";  next }
+        /.*Succeeded.*/  {print "\\033[0;32m" \$0 "\\033[0;30m";  next }
+
+        # everything else, print in black
+        /.*/            {print "\\033[0;30m" \$0 "\\033[0;30m" ; }
+      '
+      return \${PIPESTATUS[0]}
+    }
+
 
   cleanup: &cleanup |
-    export PATH=/usr/local/bin:$PATH
+    export PATH=/usr/local/bin:\$PATH
     # clean up the stuff from previous runs
     # due to the length of the jobname workspace, we are hitting limits in
     # our sheebang path name in pip.
@@ -35,10 +95,14 @@ common_cli:
     . /tmp/pip.sh
 
   setup_flocker_modules: &setup_flocker_modules |
-    pip install --upgrade pip
-    pip install -i \$PIP_INDEX_URL . --trusted-host \$TRUSTED_HOST
-    pip install -i \$PIP_INDEX_URL "Flocker[doc,dev,release]" --trusted-host \$TRUSTED_HOST
-    pip install -i \$PIP_INDEX_URL python-subunit junitxml  --trusted-host \$TRUSTED_HOST
+    # upgrade pip, we need pip 7.1 (--trusted-host option)
+    parse_logs pip install --upgrade pip
+    # using the caching-layer, install all the dependencies
+    parse_logs pip install -i \$PIP_INDEX_URL . --trusted-host \$TRUSTED_HOST
+    # using the caching-layer, install flocker
+    parse_logs pip install -i \$PIP_INDEX_URL "Flocker[doc,dev,release]" --trusted-host \$TRUSTED_HOST
+    # using the caching-layer, install junix for our coverage report
+    parse_logs pip install -i \$PIP_INDEX_URL python-subunit junitxml  --trusted-host \$TRUSTED_HOST
 
   setup_aws_env_vars: &setup_aws_env_vars |
     # set vars and run tests
@@ -47,25 +111,29 @@ common_cli:
     export FLOCKER_FUNCTIONAL_TEST_CLOUD_PROVIDER=aws
 
   setup_coverage: &setup_coverage |
-    pip install coverage==3.7.1 http://data.hybridcluster.net/python/coverage_reporter-0.01_hl0-py27-none-any.whl  --trusted-host \$TRUSTED_HOST
+    parse_logs pip install coverage==3.7.1 http://data.hybridcluster.net/python/coverage_reporter-0.01_hl0-py27-none-any.whl  --trusted-host \$TRUSTED_HOST
 
   run_coverage: &run_coverage |
-    coverage xml --include=flocker*
+    parse_logs coverage xml --include=flocker*
 
   convert_results_to_junit: &convert_results_to_junit |
     cat trial.log | subunit-1to2 | subunit2junitxml --no-passthrough --output-to=results.xml
 
   run_sphinx: &run_sphinx |
-    python setup.py --version
+    parse_logs python setup.py --version
     cd docs
     set +e #don't abort at the first failure
     let status=0
-    sphinx-build -d _build/doctree -b spelling . _build/spelling
+    # check spelling
+    parse_logs sphinx-build -d _build/doctree -b spelling . _build/spelling
     let status=status+\$?
-    sphinx-build -d _build/doctree -b linkcheck . _build/linkcheck
+    # check links
+    parse_logs sphinx-build -d _build/doctree -b linkcheck . _build/linkcheck
     let status=status+\$?
-    sphinx-build -d _build/doctree -b html . _build/html
+    # build html pages
+    parse_logs sphinx-build -d _build/doctree -b html . _build/html
     exit \$status
+    # TODO:
     # upload html
     #link-release-documentation
     #upload-release-documentation
@@ -78,7 +146,7 @@ common_cli:
 
   run_trial_with_coverage: &run_trial_with_coverage |
     # Consume the MODULE parameter set in the job configuration
-    coverage run /tmp/v/bin/trial --reporter=subunit \$MODULE 2>&1 | tee trial.log
+    coverage run /tmp/v/bin/trial --reporter=subunit \$MODULE 2>&1 | parse_logs tee trial.log
 
   setup_authentication: &setup_authentication |
     # acceptance tests rely on this file existing
@@ -93,7 +161,7 @@ common_cli:
 
   run_acceptance_tests: &run_acceptance_tests |
     # we gather the return code, but make sure we come out of these tests with '0'
-    /tmp/v/bin/python admin/run-acceptance-tests --distribution \${DISTRIBUTION_NAME} --provider aws --dataset-backend aws --branch \${TRIGGERED_BRANCH} --build-server  http://\$(wget -qO- http://instance-data/latest/meta-data/public-ipv4)  --config-file /tmp/acceptance.yaml \${ACCEPTANCE_TEST_MODULE} ; RC=\$?
+    parse_logs /tmp/v/bin/python admin/run-acceptance-tests --distribution \${DISTRIBUTION_NAME} --provider aws --dataset-backend aws --branch \${TRIGGERED_BRANCH} --build-server  http://\$(wget -qO- http://instance-data/latest/meta-data/public-ipv4)  --config-file /tmp/acceptance.yaml \${ACCEPTANCE_TEST_MODULE} ; RC=\$?
 
   disable_selinux: &disable_selinux |
     sudo setenforce 0
@@ -102,10 +170,12 @@ common_cli:
     export FLOCKER_VERSION=\$(/tmp/v/bin/python setup.py --version)
 
   build_sdist: &build_sdist  |
-    /tmp/v/bin/python setup.py sdist
+    # package the goodies
+    parse_logs /tmp/v/bin/python setup.py sdist
 
   build_package: &build_package  |
-    /tmp/v/bin/python admin/build-package --destination-path repo --distribution \${DISTRIBUTION_NAME} /flocker/dist/Flocker-\${FLOCKER_VERSION}.tar.gz
+    # and build a rpm/deb package using docker
+    parse_logs /tmp/v/bin/python admin/build-package --destination-path repo --distribution \${DISTRIBUTION_NAME} /flocker/dist/Flocker-\${FLOCKER_VERSION}.tar.gz
 
   setup_hosting_for_packages: &setup_hosting_for_packages |
       # the acceptance tests look for a package in a yum repository,
@@ -203,7 +273,7 @@ job_type:
         - flocker.volume
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules, *setup_coverage, *setup_aws_env_vars,
                    *run_trial_with_coverage, *run_coverage,
                    *convert_results_to_junit ]
@@ -240,7 +310,7 @@ job_type:
         - flocker.volume
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules, *setup_coverage, *setup_aws_env_vars,
                    *run_trial_with_coverage, *run_coverage,
                    *convert_results_to_junit ]
@@ -254,7 +324,7 @@ job_type:
       on_nodes_with_labels: 'aws-centos-7-T2Micro'
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules, *setup_aws_env_vars,
                    *run_sphinx ]
           }
@@ -265,7 +335,7 @@ job_type:
       on_nodes_with_labels: 'aws-centos-7-M3Medium'
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules,
                    'export DISTRIBUTION_NAME=centos-7',
                    *setup_aws_env_vars, *check_version, *disable_selinux,
@@ -281,7 +351,7 @@ job_type:
       on_nodes_with_labels: 'aws-centos-7-M3Medium'
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules,
                    'export DISTRIBUTION_NAME=centos-7',
                    *setup_aws_env_vars, *check_version, *disable_selinux,
@@ -297,7 +367,7 @@ job_type:
       on_nodes_with_labels: 'aws-centos-7-M3Medium'
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules,
                    'export DISTRIBUTION_NAME=centos-7',
                    *setup_aws_env_vars, *check_version, *disable_selinux,
@@ -313,7 +383,7 @@ job_type:
       on_nodes_with_labels: 'aws-centos-7-M3Medium'
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules,
                    'export DISTRIBUTION_NAME=centos-7',
                    *setup_aws_env_vars, *check_version, *disable_selinux,
@@ -329,7 +399,7 @@ job_type:
       on_nodes_with_labels: 'aws-centos-7-M3Medium'
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules,
                    'export DISTRIBUTION_NAME=centos-7',
                    *setup_aws_env_vars, *check_version, *disable_selinux,
@@ -345,7 +415,7 @@ job_type:
       on_nodes_with_labels: 'aws-ubuntu-trusty-M3Medium'
       with_steps:
         - { type: 'shell',
-            cli: [ *hashbang, *setup_pip_cache,
+            cli: [ *hashbang,  *setup_pip_cache,
                    *cleanup, *setup_venv, *setup_flocker_modules,
                    'export DISTRIBUTION_NAME=ubuntu-14.04',
                    *setup_aws_env_vars, *check_version,
